GET http://localhost:8081/api/movies/d39cba4a-f62e-4424-9e95-8f1dd03904f0

###
POST http://localhost:8081/api/movies
Content-Type: application/json

{
  "title": "A Quiet Place",
  "description": "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.",
  "genre": "HORROR",
  "duration": "PT1H30M",
  "releaseDate": "2018-04-13",
  "score": "7.5",
  "thumbnail": "https://thumbnails.com/quiet-place",
  "director": {
    "name": "John",
    "surname": "Krasinski",
    "birthDate": "1979-10-20"
  }
}
###
GET http://localhost:8081/api/movies

###
DELETE http://localhost:8081/api/movies/d39cba4a-f62e-4424-9e95-8f1dd03904f0

###
DELETE http://localhost:8080/api/movies?genre=ACTION
