GET http://localhost:8081/api/movies?size=3&page=0&sort=releaseDate,asc

###
GET http://localhost:8081/api/movies?size=3&page=0&sort=releaseDate,desc

###
GET http://localhost:8081/api/movies?title=r

###
GET http://localhost:8081/api/popular-movies

###
PUT http://localhost:8081/api/movies/3f274737-d74a-4e51-aee6-72bfac54d6c3
Content-Type: application/json

{
  "title": "Ciche miejsce",
  "description": "W postapokaliptycznym świecie rodzina zmuszona jest żyć w ciszy, ukrywając się przed potworami o bardzo czułym słuchu.",
  "genre": "COMEDY",
  "duration": "PT1H30M",
  "releaseDate": "2018-04-13",
  "score": "9.9",
  "thumbnail": "https://thumbnails.com/ciche-place",
  "director": {
    "name": "John",
    "surname": "Krasinski",
    "birthDate": "1979-10-20"
  }
}
